apiVersion: apps/v1
kind: Deployment
metadata:
    name: post
    labels:
        app: post
spec:
    replicas: 2
    selector:
        matchLabels:
            app: post
    template:
        metadata:
            labels:
                app: post
        spec:
            containers:
                - name: post
                  image: 21lucasmessias/udemy-micro:post_0.3
                  env:
                      - name: 'PORT'
                        value: '3000'
                      - name: 'EVENT_BUS_PORT'
                        value: '3005'
                  resources:
                      limits:
                          cpu: '0.5'
                          memory: '512Mi'
                      requests:
                          cpu: '0.1'
                          memory: '256Mi'
