apiVersion: v1
kind: Pod

metadata:
    name: post
    labels:
        app: post

spec:
    containers:
        - name: post
          image: 21lucasmessias/udemy-micro:post_0.1
        #   ports:
        #       - containerPort: 3000
        #   resources:
        #       limits:
        #           cpu: '0.5'
        #           memory: '512Mi'
