apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: post
    labels:
        app: post
spec:
    replicas: 2
    selector:
        matchLabels:
            app: post
    template:
        metadata:
            labels:
                app: post
        spec:
            containers:
                - name: post
                  image: 21lucasmessias/udemy-micro:post_0.1
