apiVersion: v1
kind: Service
metadata:
    name: post-service
spec:
    selector:
        app: post
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 3000
          name: post-service
